### ISSUE TITLE
MAUI - Unknown network error EOF

### ISSUE THREAD

**Issue by dimitri-dev** [segmentio/Analytics-CSharp#103]
**Describe the bug**
Segment.Analytics.AnalyticsError
Unknown network error when uploading to url
-> unexpected end of stream on com.android.okhttp.Address@1599a963
-> \n not found: size=0 content=...

**To Reproduce**
Just occurs in the background while running a .NET 8 (Runtime 8.0.4) MAUI app.
This is just a (relatively) simple native Android and iOS project.

**Raw stack trace**
> Java.IO.IOException: unexpected end of stream on com.android.okhttp.Address@1599a963
  ?, in int InstanceMethods.CallIntMethod(JniObjectReference, JniMethodInfo, JniArgumentValue*)
  ?, in int JniInstanceMethods.InvokeVirtualInt32Method(string, IJavaPeerable, JniArgumentValue*)
  ?, in HttpStatus HttpURLConnection.get_ResponseCode()
  ?, in Task<HttpResponseMessage> AndroidMessageHandler.DoProcessRequest(HttpRequestMessage, URL, HttpURLConnection, CancellationToken, RequestRedirectionState)+() => { }
  ?, in void Task<HttpStatusCode>.InnerInvoke()
  ?, in async Task<HttpResponseMessage> AndroidMessageHandler.DoProcessRequest(HttpRequestMessage, URL, HttpURLConnection, CancellationToken, RequestRedirectionState)
  ?, in async Task<HttpResponseMessage> AndroidMessageHandler.DoSendAsync(HttpRequestMessage, CancellationToken)
System.Net.WebException: unexpected end of stream on com.android.okhttp.Address@1599a963
  ?, in async Task<HttpResponseMessage> AndroidMessageHandler.DoSendAsync(HttpRequestMessage, CancellationToken)
  ?, in async Task<HttpResponseMessage> HttpClient.SendAsync(HttpRequestMessage)+Core(?)
  ?, in async Task<Response> DefaultHTTPClient.DoPost(string url, byte[] data)
  ?, in async Task<bool> HTTPClient.Upload(byte[] data)

**Additional context**
Currently using Segment.Analytics.CSharp 2.3.5.0 release.

**Comment by dimitri-dev** [comment]
@wenxi-zeng I'm not sure if this is the best way to go about this, but if you can take a look at #104, it should solve this issue as I've already encountered it in MAUI recently.

**Comment by wenxi-zeng** [comment]
hi @dimitri-dev, thanks for contributing! the pr looks good. we will thoroughly test it on other platforms and then ship it in the next release. in the meanwhile, please write a custom httpclient as a workaround.

**Comment by wenxi-zeng** [comment]
@dimitri-dev the fix is shipped in the new release `2.4.1`. please have a try. thanks again for your contribution
