### ISSUE TITLE
Lifecycle support for WPF dotnet framework application?

### ISSUE THREAD

**Issue by arlyxiao** [segmentio/Analytics-CSharp#106]
We use the Analyics.CSharp in WPF dotnet framework application.

Here is the documentation we found that lifecycle only supports mobile only. There is no windows.
https://segment.com/blog/lifecycle-of-a-mobile-message/

And we also find that there is an unity example
https://github.com/segmentio/Analytics-CSharp/blob/main/Samples/UnitySample/LifecyclePlugin.cs

The API in the example is quite different from the lifecycle API in mobile.
Does this support WPF dotnet framework application or dotnet framework console application?

#### Platform (please complete the following information):

Library Version in use: 2.3.4
Platform being tested: WPF dotnet framework 4.8
Integrations in use:

**Comment by wenxi-zeng** [comment]
hi @arlyxiao,  we don't have example for WPF specifically, but you can take a look at this [Xamarin example](https://github.com/segmentio/Analytics-CSharp/blob/main/Samples/XamarinSample/XamarinSample/App.xaml.cs). the idea is the same. a quick search with ChatGPT gives me the following:
```
using System;
using System.Windows;

namespace WpfApp
{
    public partial class App : Application
    {
        protected override void OnStartup(StartupEventArgs e)
        {
            base.OnStartup(e);
            // Handle startup logic here
            Console.WriteLine("Application started.");
        }

        protected override void OnExit(ExitEventArgs e)
        {
            base.OnExit(e);
            // Handle exit logic here
            Console.WriteLine("Application exited.");
        }

        protected override void OnActivated(EventArgs e)
        {
            base.OnActivated(e);
            // Handle activated logic here
            Console.WriteLine("Application activated.");
        }

        protected override void OnDeactivated(EventArgs e)
        {
            base.OnDeactivated(e);
            // Handle deactivated logic here
            Console.WriteLine("Application deactivated.");
        }

        protected override void OnSessionEnding(SessionEndingCancelEventArgs e)
        {
            base.OnSessionEnding(e);
            // Handle session ending logic here
            Console.WriteLine("Session ending.");
        }
    }
}
```
Just replace `Console.WriteLine` with `analytics.track` and you are good to go
