### ISSUE TITLE
Why does the function PendingUpload unsent events

### ISSUE THREAD

**Issue by arlyxiao** [segmentio/Analytics-CSharp#112]
The function PendingUpload will be called when initialized analytics. And then remove the file without sending the events.

![1727580004498](https://github.com/user-attachments/assets/88e9b9f6-e932-44f2-84e0-d731f9250d39)

Why not send the events when initialize analytics?
If it only removes files without sending events. These events will be lost.
This doesn't make sense.

In my use case,
It should flush all old temporary before purge whatever the scenario is.

**Comment by wenxi-zeng** [comment]
hi @arlyxiao, these two functions `PendingUploads` and `PurgeStorage` are utility functions for people who wanna control the storage themselves. the SDK itself does not use these two functions for flush. if you want to flush the events before purge, simple do 
```
    analytics.Flush();  // flush events
    analytics.PurgeStorage();  // remove damaged files that can't be flushed
```
the functions only do what it intends to do. `Flush` for flushing. `Purge` for cleaning.
