### ISSUE TITLE
The cache file under Segment.Data/events can't be generated

### ISSUE THREAD

**Issue by arlyxiao** [segmentio/Analytics-CSharp#117]
First of all, I can make sure the segment write key is correct. And the events folder is generated when it's initialized.

Sometimes the cached file under the events folder can be generated.
Sometimes it can't be generated. Also it will not be uploaded. I also can make sure the function has been finished called in this case. `internal RawEvent Process(RawEvent incomingEvent)`

Which kind of possible reasons would not generate the file?

**Comment by wenxi-zeng** [comment]
@arlyxiao can you please post your configuration of analytics? make sure you are not using in-memory storage. also what platforms are you having this issue, did you customize your storage or flush policy? are you using purge and flush in the right way? they can all contribute to the issue. the latest version has been out for 3 months, we haven't heard anyone else reporting issue like this. if you have anything customized, I'd suggest switch to the default implementation and check if the issue still persists.
