### ISSUE TITLE
How's the performance behavior

### ISSUE THREAD

**Issue by arlyxiao** [segmentio/Analytics-CSharp#119]
Suppose it's offline and generates 100,0000 events in local without network.
This will create a bunch of JSON files in the events folder.

Once the network is back and available now. Then create one new event and call flush.
Which kind of behavior will it be handled? Will all of the json files be uploaded in one time?

Will this cause the UI performance issue if it uploads huge data in background continuedly?

**Comment by wenxi-zeng** [comment]
@arlyxiao the files will be scheduled to upload. the SDK runs on a different scope and coroutine entirely and uses a dedicated file thread, so no it won't impact UI. in addition, you could write your own flush policy if you worry about uploading too many files at once. if you interest in performance benchmark, please check out the following:
https://segment.com/blog/sdk-performance-improvements/
