### ISSUE TITLE
Temporary file is not generated when network is off

### ISSUE THREAD

**Issue by arlyxiao** [segmentio/Analytics-CSharp#120]
SDK version: 2.4.2
windows: dotnet framework 4.7.2

The steps below:
1. Close network
2. Create new segment instance with write key offline
3. Generate group events offline.

The 3rd step will not generate the temporary file when call track/group/screen API

**Comment by wenxi-zeng** [comment]
the SDK writes to file regardless the status of network. only uploads are network related. I'd suggest double check your implementation.

**Comment by arlyxiao** [comment]
> the SDK writes to file regardless the status of network. only uploads are network related. I'd suggest double check your implementation.

Upload behavior depends on the network status. This makes sense.

And the temporary file generated or not also rely on the network? @wenxi-zeng

**Comment by arlyxiao** [comment]
> the SDK writes to file regardless the status of network. only uploads are network related. I'd suggest double check your implementation.

About `write to file` when network is off. From my test result, it has two cases:

- case 1:
  1. Close the network.
  2. Clear all first, then create new segment instance by default config.
  3. Call API to generate events. This will not generate the temporary file.  
- case 2:
  1. Open the network.
  2. Clear all, and create new segment instance by default config.
  3. Call API to generate one event, make sure the first temporary file is generated first.
  4. Close the network and continue generating the events, This can write to the file.

In case1, if it's new and the first time to create segment and start generating events without network.
It will not write to the file. @wenxi-zeng

**Comment by wenxi-zeng** [comment]
@arlyxiao please refer to the [instruction](https://github.com/segmentio/Analytics-CSharp?tab=readme-ov-file#creating-your-own-flush-policies) on how to create your own policy
