### ISSUE TITLE
plugin behavior works on flush instead of event

### ISSUE THREAD

**Issue by arlyxiao** [segmentio/Analytics-CSharp#123]
I have one plugin which wants to override the originalTimestamp
Suppose I will fire the three events:

```
// change timestamp = 100 in plugin
segment.track

// change timestamp = 101 in plugin
segment.group

// change timestamp = 102 in plugin
segment.screen

segment.flush
```

The final result would be all of events are using the latest timestamp = 102 after flush.
But the expect result from my requirement that I want to set each event has its timestamp which can be modified by plugin.

Is that possible?

**Comment by wenxi-zeng** [comment]
please reach out to friends@segment.com with a copy of this report for futher assistance. they can better support for this type of questions
