### ISSUE TITLE
Problems on xamarin native android when internet is lost

### ISSUE THREAD

**Issue by Oleg-0** [segmentio/Analytics-CSharp#63]
We are using analytics-csharp library for our xamarin native android app to track events to Segment.  It works well, but there are two problems.
1) if there is no Internet at the time of SDK initialization, then even after it is restored, events are not sent
2) if at the time of SDK initialization there was internet, then it disappeared, then it was restored, events that were generated without internet are not sent.
do we need some additional setup?

**Comment by wenxi-zeng** [comment]
hey @Oleg-0 thanks for reporting this issue. events should be retried after internet restored. can you try a manual `analytics.Flush()` to see if any events get flushed to server after network restoration. I'll take a look into this too.

we're going to release our GA version this week, which provides a flush policy that lets you customize when and how you want to flush. you'll soon be able to define your own way to flush in scenarios like this.

**Comment by wenxi-zeng** [comment]
hey @Oleg-0 we've spotted and fixed the issue. will get a release out soon.

**Comment by Oleg-0** [comment]
thank you very much! Does this also apply to the first part of the problem, that if at the time of SDK initialization there is no Internet, then even after it is restored, events, even new ones, are not sent?

**Comment by wenxi-zeng** [comment]
hey @Oleg-0 ,we have released `2.3.0-alpha.2` that has the fix to the issue. note that this is a pre-release version which is meant for testing. use it as an urgent fix. the official `2.3.0` will be out in 2 days.

**Comment by Oleg-0** [comment]
Thanks!
