### ISSUE TITLE
UnauthorizedAccessException raised by Analytics type constructor when deployed to azure app service

### ISSUE THREAD

**Issue by rsuk-mb** [segmentio/Analytics-CSharp#82]
**Describe the bug**
When deploying to an azure app service, an UnauthorizedAccessException is raised when constructing an Analytics instance

**To Reproduce**
1. Create a web api that constructs a default Analytics instance - no additional configuration required
2. Deploy to an azure app service
3. Error raised during construction of the Analytics instance - "System.UnauthorizedAccessException: Access to the path 'C:\segment.data\<key>\events' is denied."

**Expected behavior**
Analytics functions without error when deployed to azure app service

**Platform (please complete the following information):**
 - Library Version in use: 3,8,1
 - Platform being tested: windows
 - Integrations in use: none

**Additional context**
I have verified through additional logging that the "Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData)" call used by the DefaultStorageProvider returns null/empty when running on an Azure App Service which seems to be the underlying cause of this issue. I also observed that Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData) also returns a null/blank value. 

Environment.GetFolderPath(Environment.SpecialFolder.CommonApplicationData) returns a value (c:\programdata), but I am pretty sure that path will not be writable on an app service given the information here - https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system. Path.GetTempPath() does return what looks like a valid and writable path - c:\local\temp.

I have worked around the issue by constructing the DefaultStorageProvider, using Path.GetTempPath() as the storage location - and passing this in as part of the Analytics constructor configuration parameter.

**Comment by wenxi-zeng** [comment]
hey @rsuk-mb, thanks for reporting this. you have the right solution here. the sdk tries its best to detect the environment and configures the storage path for you, but certainly it's impossible to cover all the platforms that .net can run. that's why we made the storage highly customizable. in your case, passing the desired the path is the simplest and effective way. other cases might require you to write your own storage provider or make it in-memory only.
