### ISSUE TITLE
Events Successfully Sent to Destination but Not Synced with Warehouse (eu portal)

### ISSUE THREAD

**Issue by mnasini** [segmentio/Analytics-CSharp#83]
hi, we are testing the Analytics-CSharp sdk and we ran into an issue: even if the events get received in our destinations, we don't see them in the debugger and either they don't get synced with the warehouse: 

to give you more informations here is the last test we made: 

1. we created a .net source in segment
2. we sent a sample track event using the sdk
3. we received the event in our destination, but not in the debugger
4. we saw that the synced rows with our warehouse remained 0 for that source

here is our configuration
`var configuration = new Configuration("***",
    flushAt: 1,
    flushInterval: 10,
    exceptionHandler: new ErrorHandler(),
    apiHost:"events.eu1.segmentapis.com/",
    storageProvider:new InMemoryStorageProvider());`

here are our logs:

Message: Analytics starting = False
Message: Segment.io performing flush
Message: Analytics starting = False
Message: Analytics starting = True
Message: Segment.io running {"type":"track","event":"h","properties":{},"anonymousId":"173a40ff-90fc-4354-950c-4c465c61eed4","messageId":"1513bb45-9e86-4638-9ad3-227ea10340e0","userId":null,"timestamp":"2024-01-29T14:20:55.7609390Z","context":{"os": "Microsoft Windows 10.0.20348","platform": ".NET","library": {"name": "Analytics-CSharp","version": "2.3.0"}},"integrations":{},"metrics":null,"_metadata":{"bundled":[],"unbundled":["segment_lambda(test_portal EU)"],"bundledIds":[]}}
Message: Segment.io performing flush
Message: Segment.io uploaded jbu5CUhUV2hWp6YN82pAz7o7ctxBB6nb-0.json
Message: Segment.io performing flush

could this problem be related to the use of the sdk? (since we are not having the same issue with other type of sources)

thanks a lot in advance

**Comment by wenxi-zeng** [comment]
hey @mnasini, thanks for reporting this issue. the Segment Debugger does not show every event arrived, instead it does a sampling on the events. If your destination has received the events, that means Segment has received it first. please reach out to our backend team in regards of the warehouse not synced issue.

**Comment by nmaricmoberg** [comment]
@mnasini Could you please try setting the ApiUrl to `events.eu1.segmentapis.com/v1`. I've experienced the same issues trying to set this SDK up until I figured that out. Also, you must build the Analytics-CSharp yourself since the ApiHost currently is not honored in the event pipeline - the changes were made in #79 (two months ago) but they're still not released...

**Comment by wenxi-zeng** [comment]
hey @nmaricmoberg, that's a good callout. I'll escalate a release and get back to you all

**Comment by wenxi-zeng** [comment]
hi @mnasini and @nmaricmoberg , `2.3.2` is out. please have a try

**Comment by nmaricmoberg** [comment]
hi @wenxi-zeng, `2.3.2` appears to be working fine with the EU api host. thank you for the escalated release! :)

**Comment by mnasini** [comment]
hello @wenxi-zeng i can confirm is working, thanks a lot to everyone!
