### ISSUE TITLE
EU API Host Release

### ISSUE THREAD

**Issue by nmaricmoberg** [segmentio/Analytics-CSharp#84]
All requests are sent to `api.segment.io/v1` regardless of the config.ApiHost value.
Upon some digging, we found that this was fixed in PR #79.

Since this is still not a released NuGet package, we cannot deploy Segment into production where we must target EU API since none of the requests come through. When can we expect a package release?

Sidenote:
I was really surprised that this SDK, [Analytics-CSharp](https://github.com/segmentio/Analytics-CSharp), does not append the /v1/ in code. It does, however, append https:// at the start? The reason why I was surprised is that the previous C#/Xamarin SDK, [Analytics.Xamarin](https://github.com/segmentio/Analytics.Xamarin) does append /v1/ in code (although not the https).

This sort of SDK change is documented nowhere at all in the migration guide or in the docs here. It can cause a lot of undefined behavior when configuring your API host. I believe you should include the EU region host in the README file to avoid any confusion in regards to this. (it should be `events.eu1.segmentapis.com/v1`)

**Comment by wenxi-zeng** [comment]
thanks @nmaricmoberg for bring this to our attention. we will get the release out asap and add the note to readme

**Comment by wenxi-zeng** [comment]
@nmaricmoberg the new release 2.3.2 is out. we will work with our doc team to get the note of endpoints added to the migration guide. thanks again for reporting this issue!

**Comment by nmaricmoberg** [comment]
@wenxi-zeng In regards to the docs, I have opened an issue on the docs repository as well, you can take a look at it here:
https://github.com/segmentio/segment-docs/issues/5943

**Comment by wenxi-zeng** [comment]
thanks @nmaricmoberg! the c# migration guide will soon be updated with a note on the eu endpoint difference. the issue you opened on segment-docs is a general guide for all libraries. all the next gen server libraries (kotlin/swift/c#) now no longer include v1 as part of the url, but the legacy ones still do. I'll leave them to decide how to change the language on the regional guide
