### ISSUE TITLE
Analytics Startup logs an error after waking up from appPool time out

### ISSUE THREAD

**Issue by Chiel75** [segmentio/Analytics-CSharp#90]
We use the Analyics.CSharp in an ASP.Net project. After the appPool times out, the memory is cleared.
When the website is waking up again because of user activity, the Analytics StartUp() is called again (as it should because we registrered the Analytics as a singleton).
After waking up, in the StartUp() is tried to:
                    await Store.Provide(System.DefaultState(Configuration, Storage));
In the DefaultState method the cache is read from the storage (in this case the lost inmemorystream because of the appPool) and returns an empty string variable cache. After that, the empty cache string will generate an exception that is being logged.

**Expected behavior**
No uneccesary exception should be thrown. Maybe an info message the the state could not be found from the cache.

**Platform (please complete the following information):**
 - Library Version in use: 2.3.2
 - Platform being tested: ASP.Net
 - Integrations in use:

**Comment by wenxi-zeng** [comment]
@Chiel75 just want o clarify, are you referring to this [line](https://github.com/segmentio/Analytics-CSharp/blob/main/Analytics-CSharp/Segment/Analytics/State.cs#L44) that logs as an error should instead log as info?

**Comment by Chiel75** [comment]
Hi @wenxi-zeng No, but if this [line](https://github.com/segmentio/Analytics-CSharp/blob/665b700116cf712eb97c8505d614372875fd69a1/Analytics-CSharp/Segment/Analytics/State.cs#L39C24-L39C30) results in an empty string, there is no need to try and deserialize it into a settings object and let it throw an exception.

**Comment by wenxi-zeng** [comment]
@Chiel75 sorry for the late response. after discussion, our team also feel we should log the empty string case as an info, but keep the deserialization case as an exception. we will push an update for this in the next release.

**Comment by wenxi-zeng** [comment]
fixed in `2.3.4`
